// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"
)

const clearFileExpiry = `-- name: ClearFileExpiry :one
UPDATE files
SET expires_at = NULL,
    max_views = NULL,
    view_count = 0,
    expired_at = NULL,
    expired_reason = '',
    updated_at = CURRENT_TIMESTAMP
WHERE slug = ?1 AND user_id = ?2 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id, expired_at, expired_reason, content_size
`

type ClearFileExpiryParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) ClearFileExpiry(ctx context.Context, arg ClearFileExpiryParams) (File, error) {
	row := q.db.QueryRowContext(ctx, clearFileExpiry, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
		&i.ExpiredAt,
		&i.ExpiredReason,
		&i.ContentSize,
	)
	return i, err
}

const createFile = `-- name: CreateFile :one

INSERT INTO files (slug, name, html_content, content_size, kind, is_public, access_code, user_id)
VALUES (
    ?1,
    ?2,
    ?3,
    length(CAST(?3 AS BLOB)),
    ?4,
    ?5,
    ?6,
    ?7
)
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id, expired_at, expired_reason, content_size
`

type CreateFileParams struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	HtmlContent string `json:"html_content"`
	Kind        string `json:"kind"`
	IsPublic    bool   `json:"is_public"`
	AccessCode  string `json:"access_code"`
	UserID      int64  `json:"user_id"`
}

// ===========================================================================
// OWNER-SCOPED -- everything reachable from a request behind requireAuth.
//
// Every query below carries `user_id = sqlc.arg(user_id)`, so a slug belonging
// to another user simply doesn't match: reads return sql.ErrNoRows and writes
// affect 0 rows, which handlers turn into the same 404 a nonexistent slug
// gets. Ownership therefore lives in the schema, not in a Go check a caller
// can forget -- and because sqlc runs with emit_interface: false, dropping the
// predicate from a query breaks the build at every call site.
//
// New file queries belong in this section and MUST carry the predicate.
// ===========================================================================
// content_size is derived from html_content by the statement itself, here and
// in UpdateFile, so the two can never drift: there is no way to write the
// content through this schema without writing its size in the same statement.
// length(CAST(x AS BLOB)) is bytes; bare length() on TEXT counts characters.
func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.Slug,
		arg.Name,
		arg.HtmlContent,
		arg.Kind,
		arg.IsPublic,
		arg.AccessCode,
		arg.UserID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
		&i.ExpiredAt,
		&i.ExpiredReason,
		&i.ContentSize,
	)
	return i, err
}

const deleteUserFiles = `-- name: DeleteUserFiles :execrows

DELETE FROM files
WHERE user_id = ?1
`

// ===========================================================================
// ADMIN CASCADE -- account deletion only (DELETE /api/admin/users/{id}).
//
// This one carries user_id like everything above it, but the id is the
// *target account's*, never the caller's, so the owner-scoping argument that
// protects the section above does not apply here: the predicate cannot stop a
// caller from naming someone else, only the super-admin check in the handler
// can. It also has no deleted_at guard -- deleting an account takes its trash
// with it, which is the point -- so unlike HardDeleteUserTrash there is no
// second predicate standing between a mistake and every file the account owns.
// Call it from AdminHandler.Delete and nowhere else, inside its transaction.
// ===========================================================================
func (q *Queries) DeleteUserFiles(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUserFiles, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const expireFile = `-- name: ExpireFile :exec
UPDATE files
SET is_public = 0,
    expires_at = NULL,
    max_views = NULL,
    expired_at = CURRENT_TIMESTAMP,
    expired_reason = ?1
WHERE slug = ?2 AND deleted_at IS NULL
`

type ExpireFileParams struct {
	ExpiredReason string `json:"expired_reason"`
	Slug          string `json:"slug"`
}

// Taking a file offline records why, overwriting any earlier event: only the
// most recent one is kept, which is all the dashboard badge claims to show.
func (q *Queries) ExpireFile(ctx context.Context, arg ExpireFileParams) error {
	_, err := q.db.ExecContext(ctx, expireFile, arg.ExpiredReason, arg.Slug)
	return err
}

const getFileBySlugAnyOwner = `-- name: GetFileBySlugAnyOwner :one

SELECT files.id, files.slug, files.name, files.html_content, files.is_public, files.access_code, files.created_at, files.updated_at, files.deleted_at, files.success_count, files.failure_count, files.tags, files.expires_at, files.max_views, files.view_count, files.kind, files.code_success_count, files.user_id, files.expired_at, files.expired_reason, files.content_size FROM files
JOIN users ON users.id = files.user_id
WHERE files.slug = ? AND files.deleted_at IS NULL AND users.disabled_at IS NULL
`

// ===========================================================================
// UNSCOPED -- the public render path (GET /res/{slug}) only.
//
// These serve anonymous visitors holding a share link, who have no user at
// all, so they cannot be owner-scoped without breaking every public link.
// NEVER call anything below this line from a handler behind requireAuth --
// that is exactly how the IDOR this section exists to prevent was introduced.
// See FilesHandler.Render.
// ===========================================================================
// The join is the enforcement point for account suspension: a suspended
// owner's files simply match no row here, so every one of their share links
// becomes the same 404 a slug that never existed gets. Doing it in SQL rather
// than as a Go check after the fact means the render path cannot forget.
func (q *Queries) GetFileBySlugAnyOwner(ctx context.Context, slug string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileBySlugAnyOwner, slug)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
		&i.ExpiredAt,
		&i.ExpiredReason,
		&i.ContentSize,
	)
	return i, err
}

const getUserFileBySlug = `-- name: GetUserFileBySlug :one
SELECT id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id, expired_at, expired_reason, content_size FROM files
WHERE slug = ?1 AND user_id = ?2 AND deleted_at IS NULL
`

type GetUserFileBySlugParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) GetUserFileBySlug(ctx context.Context, arg GetUserFileBySlugParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getUserFileBySlug, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
		&i.ExpiredAt,
		&i.ExpiredReason,
		&i.ContentSize,
	)
	return i, err
}

const getUserFileSize = `-- name: GetUserFileSize :one
SELECT content_size FROM files
WHERE slug = ?1 AND user_id = ?2 AND deleted_at IS NULL
`

type GetUserFileSizeParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

// What an edit is replacing, so the quota check can subtract it instead of
// charging the account twice for a file it already stores.
func (q *Queries) GetUserFileSize(ctx context.Context, arg GetUserFileSizeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getUserFileSize, arg.Slug, arg.UserID)
	var content_size int64
	err := row.Scan(&content_size)
	return content_size, err
}

const hardDeleteFile = `-- name: HardDeleteFile :execrows
DELETE FROM files
WHERE slug = ?1 AND user_id = ?2 AND deleted_at IS NOT NULL
`

type HardDeleteFileParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) HardDeleteFile(ctx context.Context, arg HardDeleteFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, hardDeleteFile, arg.Slug, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const hardDeleteUserTrash = `-- name: HardDeleteUserTrash :execrows
DELETE FROM files
WHERE user_id = ?1 AND deleted_at IS NOT NULL
`

// Empty the trash. deleted_at IS NOT NULL is the whole safety property here:
// this is the only unbounded delete in the file, so if that predicate is ever
// dropped it takes the user's live files with it.
func (q *Queries) HardDeleteUserTrash(ctx context.Context, userID int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, hardDeleteUserTrash, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const incrementFileCodeSuccessCount = `-- name: IncrementFileCodeSuccessCount :exec
UPDATE files
SET code_success_count = code_success_count + 1
WHERE slug = ? AND deleted_at IS NULL
`

func (q *Queries) IncrementFileCodeSuccessCount(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, incrementFileCodeSuccessCount, slug)
	return err
}

const incrementFileFailureCount = `-- name: IncrementFileFailureCount :exec
UPDATE files
SET failure_count = failure_count + 1
WHERE slug = ? AND deleted_at IS NULL
`

func (q *Queries) IncrementFileFailureCount(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, incrementFileFailureCount, slug)
	return err
}

const incrementFileSuccessCount = `-- name: IncrementFileSuccessCount :exec
UPDATE files
SET success_count = success_count + 1
WHERE slug = ? AND deleted_at IS NULL
`

func (q *Queries) IncrementFileSuccessCount(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, incrementFileSuccessCount, slug)
	return err
}

const incrementFileViewCount = `-- name: IncrementFileViewCount :exec
UPDATE files
SET view_count = view_count + 1
WHERE slug = ? AND deleted_at IS NULL
`

func (q *Queries) IncrementFileViewCount(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, incrementFileViewCount, slug)
	return err
}

const listUserDeletedFiles = `-- name: ListUserDeletedFiles :many
SELECT id, slug, name, is_public, access_code, created_at, updated_at, deleted_at,
       success_count, failure_count, tags, expires_at, max_views, view_count,
       kind, code_success_count, user_id, expired_at, expired_reason, content_size
FROM files
WHERE deleted_at IS NOT NULL AND user_id = ?1
ORDER BY deleted_at DESC
`

type ListUserDeletedFilesRow struct {
	ID               int64         `json:"id"`
	Slug             string        `json:"slug"`
	Name             string        `json:"name"`
	IsPublic         bool          `json:"is_public"`
	AccessCode       string        `json:"access_code"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	DeletedAt        sql.NullTime  `json:"deleted_at"`
	SuccessCount     int64         `json:"success_count"`
	FailureCount     int64         `json:"failure_count"`
	Tags             string        `json:"tags"`
	ExpiresAt        sql.NullTime  `json:"expires_at"`
	MaxViews         sql.NullInt64 `json:"max_views"`
	ViewCount        int64         `json:"view_count"`
	Kind             string        `json:"kind"`
	CodeSuccessCount int64         `json:"code_success_count"`
	UserID           int64         `json:"user_id"`
	ExpiredAt        sql.NullTime  `json:"expired_at"`
	ExpiredReason    string        `json:"expired_reason"`
	ContentSize      int64         `json:"content_size"`
}

func (q *Queries) ListUserDeletedFiles(ctx context.Context, userID int64) ([]ListUserDeletedFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserDeletedFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserDeletedFilesRow
	for rows.Next() {
		var i ListUserDeletedFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IsPublic,
			&i.AccessCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SuccessCount,
			&i.FailureCount,
			&i.Tags,
			&i.ExpiresAt,
			&i.MaxViews,
			&i.ViewCount,
			&i.Kind,
			&i.CodeSuccessCount,
			&i.UserID,
			&i.ExpiredAt,
			&i.ExpiredReason,
			&i.ContentSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFiles = `-- name: ListUserFiles :many
SELECT id, slug, name, is_public, access_code, created_at, updated_at, deleted_at,
       success_count, failure_count, tags, expires_at, max_views, view_count,
       kind, code_success_count, user_id, expired_at, expired_reason, content_size
FROM files
WHERE deleted_at IS NULL AND user_id = ?1
ORDER BY created_at DESC
`

type ListUserFilesRow struct {
	ID               int64         `json:"id"`
	Slug             string        `json:"slug"`
	Name             string        `json:"name"`
	IsPublic         bool          `json:"is_public"`
	AccessCode       string        `json:"access_code"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	DeletedAt        sql.NullTime  `json:"deleted_at"`
	SuccessCount     int64         `json:"success_count"`
	FailureCount     int64         `json:"failure_count"`
	Tags             string        `json:"tags"`
	ExpiresAt        sql.NullTime  `json:"expires_at"`
	MaxViews         sql.NullInt64 `json:"max_views"`
	ViewCount        int64         `json:"view_count"`
	Kind             string        `json:"kind"`
	CodeSuccessCount int64         `json:"code_success_count"`
	UserID           int64         `json:"user_id"`
	ExpiredAt        sql.NullTime  `json:"expired_at"`
	ExpiredReason    string        `json:"expired_reason"`
	ContentSize      int64         `json:"content_size"`
}

// The two listings and the name search deliberately do NOT select
// html_content. They used to be SELECT *, which read every document's full
// source out of SQLite so the handler could blank the field before encoding --
// 350MB of RSS to answer a 13KB request for an account holding 160MB. Anything
// added here must stay off html_content; GetUserFileBySlug is the endpoint that
// returns content, and it returns one row.
func (q *Queries) ListUserFiles(ctx context.Context, userID int64) ([]ListUserFilesRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserFilesRow
	for rows.Next() {
		var i ListUserFilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IsPublic,
			&i.AccessCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SuccessCount,
			&i.FailureCount,
			&i.Tags,
			&i.ExpiresAt,
			&i.MaxViews,
			&i.ViewCount,
			&i.Kind,
			&i.CodeSuccessCount,
			&i.UserID,
			&i.ExpiredAt,
			&i.ExpiredReason,
			&i.ContentSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshFileAccessCode = `-- name: RefreshFileAccessCode :one
UPDATE files
SET access_code = ?1, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?2 AND user_id = ?3 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id, expired_at, expired_reason, content_size
`

type RefreshFileAccessCodeParams struct {
	AccessCode string `json:"access_code"`
	Slug       string `json:"slug"`
	UserID     int64  `json:"user_id"`
}

func (q *Queries) RefreshFileAccessCode(ctx context.Context, arg RefreshFileAccessCodeParams) (File, error) {
	row := q.db.QueryRowContext(ctx, refreshFileAccessCode, arg.AccessCode, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
		&i.ExpiredAt,
		&i.ExpiredReason,
		&i.ContentSize,
	)
	return i, err
}

const renameFile = `-- name: RenameFile :one
UPDATE files
SET name = ?1, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?2 AND user_id = ?3 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id, expired_at, expired_reason, content_size
`

type RenameFileParams struct {
	Name   string `json:"name"`
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) RenameFile(ctx context.Context, arg RenameFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, renameFile, arg.Name, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
		&i.ExpiredAt,
		&i.ExpiredReason,
		&i.ContentSize,
	)
	return i, err
}

const restoreFile = `-- name: RestoreFile :one
UPDATE files
SET deleted_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?1 AND user_id = ?2 AND deleted_at IS NOT NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id, expired_at, expired_reason, content_size
`

type RestoreFileParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) RestoreFile(ctx context.Context, arg RestoreFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, restoreFile, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
		&i.ExpiredAt,
		&i.ExpiredReason,
		&i.ContentSize,
	)
	return i, err
}

const searchUserFilesByName = `-- name: SearchUserFilesByName :many

SELECT id, slug, name, is_public, access_code, created_at, updated_at, deleted_at,
       success_count, failure_count, tags, expires_at, max_views, view_count,
       kind, code_success_count, user_id, expired_at, expired_reason, content_size
FROM files
WHERE deleted_at IS NULL AND user_id = ?1
  AND instr(lower(name), lower(?2)) > 0
ORDER BY created_at DESC
`

type SearchUserFilesByNameParams struct {
	UserID    int64  `json:"user_id"`
	NameQuery string `json:"name_query"`
}

type SearchUserFilesByNameRow struct {
	ID               int64         `json:"id"`
	Slug             string        `json:"slug"`
	Name             string        `json:"name"`
	IsPublic         bool          `json:"is_public"`
	AccessCode       string        `json:"access_code"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	DeletedAt        sql.NullTime  `json:"deleted_at"`
	SuccessCount     int64         `json:"success_count"`
	FailureCount     int64         `json:"failure_count"`
	Tags             string        `json:"tags"`
	ExpiresAt        sql.NullTime  `json:"expires_at"`
	MaxViews         sql.NullInt64 `json:"max_views"`
	ViewCount        int64         `json:"view_count"`
	Kind             string        `json:"kind"`
	CodeSuccessCount int64         `json:"code_success_count"`
	UserID           int64         `json:"user_id"`
	ExpiredAt        sql.NullTime  `json:"expired_at"`
	ExpiredReason    string        `json:"expired_reason"`
	ContentSize      int64         `json:"content_size"`
}

// Plain substring search via instr() rather than LIKE: no wildcard/escape
// handling needed, and lower() gives the same ASCII-only case-insensitivity
// LIKE would.
func (q *Queries) SearchUserFilesByName(ctx context.Context, arg SearchUserFilesByNameParams) ([]SearchUserFilesByNameRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUserFilesByName, arg.UserID, arg.NameQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUserFilesByNameRow
	for rows.Next() {
		var i SearchUserFilesByNameRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IsPublic,
			&i.AccessCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SuccessCount,
			&i.FailureCount,
			&i.Tags,
			&i.ExpiresAt,
			&i.MaxViews,
			&i.ViewCount,
			&i.Kind,
			&i.CodeSuccessCount,
			&i.UserID,
			&i.ExpiredAt,
			&i.ExpiredReason,
			&i.ContentSize,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUserFilesWithContent = `-- name: SearchUserFilesWithContent :many
SELECT id, slug, name, is_public, access_code, created_at, updated_at, deleted_at,
       success_count, failure_count, tags, expires_at, max_views, view_count,
       kind, code_success_count, user_id, expired_at, expired_reason, content_size,
       CAST(instr(lower(html_content), lower(?1)) AS INTEGER) AS match_pos,
       CAST(length(html_content) AS INTEGER) AS content_chars,
       CAST(substr(html_content,
              MAX(1, instr(lower(html_content), lower(?1)) - 100),
              length(?1) + 200) AS TEXT) AS snippet_window
FROM files
WHERE deleted_at IS NULL AND user_id = ?2
  AND (instr(lower(name), lower(?3)) > 0
    OR instr(lower(html_content), lower(?1)) > 0)
ORDER BY created_at DESC
`

type SearchUserFilesWithContentParams struct {
	ContentQuery string `json:"content_query"`
	UserID       int64  `json:"user_id"`
	NameQuery    string `json:"name_query"`
}

type SearchUserFilesWithContentRow struct {
	ID               int64         `json:"id"`
	Slug             string        `json:"slug"`
	Name             string        `json:"name"`
	IsPublic         bool          `json:"is_public"`
	AccessCode       string        `json:"access_code"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	DeletedAt        sql.NullTime  `json:"deleted_at"`
	SuccessCount     int64         `json:"success_count"`
	FailureCount     int64         `json:"failure_count"`
	Tags             string        `json:"tags"`
	ExpiresAt        sql.NullTime  `json:"expires_at"`
	MaxViews         sql.NullInt64 `json:"max_views"`
	ViewCount        int64         `json:"view_count"`
	Kind             string        `json:"kind"`
	CodeSuccessCount int64         `json:"code_success_count"`
	UserID           int64         `json:"user_id"`
	ExpiredAt        sql.NullTime  `json:"expired_at"`
	ExpiredReason    string        `json:"expired_reason"`
	ContentSize      int64         `json:"content_size"`
	MatchPos         int64         `json:"match_pos"`
	ContentChars     int64         `json:"content_chars"`
	SnippetWindow    string        `json:"snippet_window"`
}

// Content search returns a bounded window around the first match instead of
// the whole document, for the same reason the listings dropped html_content: a
// query matching fifty 5MB files would otherwise pull 250MB into memory to
// render fifty 200-character excerpts.
//
// match_pos is instr()'s 1-based character offset (0 when only the name
// matched); snippet_window is up to 100 characters either side of the match.
// Both instr() and substr() count characters here, not bytes, so the window is
// rune-safe and the handler only has to decide about ellipses.
func (q *Queries) SearchUserFilesWithContent(ctx context.Context, arg SearchUserFilesWithContentParams) ([]SearchUserFilesWithContentRow, error) {
	rows, err := q.db.QueryContext(ctx, searchUserFilesWithContent, arg.ContentQuery, arg.UserID, arg.NameQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUserFilesWithContentRow
	for rows.Next() {
		var i SearchUserFilesWithContentRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IsPublic,
			&i.AccessCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SuccessCount,
			&i.FailureCount,
			&i.Tags,
			&i.ExpiresAt,
			&i.MaxViews,
			&i.ViewCount,
			&i.Kind,
			&i.CodeSuccessCount,
			&i.UserID,
			&i.ExpiredAt,
			&i.ExpiredReason,
			&i.ContentSize,
			&i.MatchPos,
			&i.ContentChars,
			&i.SnippetWindow,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFileExpiry = `-- name: SetFileExpiry :one
UPDATE files
SET is_public = 1,
    expires_at = ?1,
    max_views = ?2,
    view_count = 0,
    expired_at = NULL,
    expired_reason = '',
    updated_at = CURRENT_TIMESTAMP
WHERE slug = ?3 AND user_id = ?4 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id, expired_at, expired_reason, content_size
`

type SetFileExpiryParams struct {
	ExpiresAt sql.NullTime  `json:"expires_at"`
	MaxViews  sql.NullInt64 `json:"max_views"`
	Slug      string        `json:"slug"`
	UserID    int64         `json:"user_id"`
}

// Both expiry writers clear expired_at/expired_reason: that marker records the
// last time a limit took the file offline, and leaving it set next to a freshly
// configured (or freshly removed) limit would contradict the file's own state.
func (q *Queries) SetFileExpiry(ctx context.Context, arg SetFileExpiryParams) (File, error) {
	row := q.db.QueryRowContext(ctx, setFileExpiry,
		arg.ExpiresAt,
		arg.MaxViews,
		arg.Slug,
		arg.UserID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
		&i.ExpiredAt,
		&i.ExpiredReason,
		&i.ContentSize,
	)
	return i, err
}

const setFileTags = `-- name: SetFileTags :one
UPDATE files
SET tags = ?1, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?2 AND user_id = ?3 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id, expired_at, expired_reason, content_size
`

type SetFileTagsParams struct {
	Tags   string `json:"tags"`
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) SetFileTags(ctx context.Context, arg SetFileTagsParams) (File, error) {
	row := q.db.QueryRowContext(ctx, setFileTags, arg.Tags, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
		&i.ExpiredAt,
		&i.ExpiredReason,
		&i.ContentSize,
	)
	return i, err
}

const setFileVisibility = `-- name: SetFileVisibility :one
UPDATE files
SET is_public = ?1, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?2 AND user_id = ?3 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id, expired_at, expired_reason, content_size
`

type SetFileVisibilityParams struct {
	IsPublic bool   `json:"is_public"`
	Slug     string `json:"slug"`
	UserID   int64  `json:"user_id"`
}

func (q *Queries) SetFileVisibility(ctx context.Context, arg SetFileVisibilityParams) (File, error) {
	row := q.db.QueryRowContext(ctx, setFileVisibility, arg.IsPublic, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
		&i.ExpiredAt,
		&i.ExpiredReason,
		&i.ContentSize,
	)
	return i, err
}

const softDeleteFile = `-- name: SoftDeleteFile :execrows
UPDATE files
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?1 AND user_id = ?2 AND deleted_at IS NULL
`

type SoftDeleteFileParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

// :execrows rather than :exec so the handler can tell "soft-deleted it" from
// "matched nothing" and 404 instead of reporting a success-shaped no-op.
func (q *Queries) SoftDeleteFile(ctx context.Context, arg SoftDeleteFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteFile, arg.Slug, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const sumUserContentSize = `-- name: SumUserContentSize :one
SELECT CAST(COALESCE(SUM(content_size), 0) AS INTEGER) AS used_bytes FROM files
WHERE user_id = ?1
`

// The caller's total stored bytes, used to enforce users.quota_bytes. Trashed
// rows are included on purpose: they still occupy the database, and emptying
// the trash is a user action, so excluding them would make soft-delete an
// unlimited quota bypass.
func (q *Queries) SumUserContentSize(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, sumUserContentSize, userID)
	var used_bytes int64
	err := row.Scan(&used_bytes)
	return used_bytes, err
}

const updateFile = `-- name: UpdateFile :one
UPDATE files
SET name = ?1,
    slug = ?2,
    html_content = ?3,
    content_size = length(CAST(?3 AS BLOB)),
    access_code = ?4,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = ?5 AND user_id = ?6 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id, expired_at, expired_reason, content_size
`

type UpdateFileParams struct {
	Name        string `json:"name"`
	NewSlug     string `json:"new_slug"`
	HtmlContent string `json:"html_content"`
	AccessCode  string `json:"access_code"`
	Slug        string `json:"slug"`
	UserID      int64  `json:"user_id"`
}

// The SET slug and the WHERE slug are different values; naming both explicitly
// keeps them from being mixed up (and avoids sqlc's generated `Slug_2` field).
func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFile,
		arg.Name,
		arg.NewSlug,
		arg.HtmlContent,
		arg.AccessCode,
		arg.Slug,
		arg.UserID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
		&i.ExpiredAt,
		&i.ExpiredReason,
		&i.ContentSize,
	)
	return i, err
}
