// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: files.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const clearFileExpiry = `-- name: ClearFileExpiry :one
UPDATE files
SET expires_at = NULL, max_views = NULL, view_count = 0, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?1 AND user_id = ?2 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id
`

type ClearFileExpiryParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) ClearFileExpiry(ctx context.Context, arg ClearFileExpiryParams) (File, error) {
	row := q.db.QueryRowContext(ctx, clearFileExpiry, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
	)
	return i, err
}

const createFile = `-- name: CreateFile :one

INSERT INTO files (slug, name, html_content, kind, is_public, access_code, user_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id
`

type CreateFileParams struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	HtmlContent string `json:"html_content"`
	Kind        string `json:"kind"`
	IsPublic    bool   `json:"is_public"`
	AccessCode  string `json:"access_code"`
	UserID      int64  `json:"user_id"`
}

// ===========================================================================
// OWNER-SCOPED -- everything reachable from a request behind requireAuth.
//
// Every query below carries `user_id = sqlc.arg(user_id)`, so a slug belonging
// to another user simply doesn't match: reads return sql.ErrNoRows and writes
// affect 0 rows, which handlers turn into the same 404 a nonexistent slug
// gets. Ownership therefore lives in the schema, not in a Go check a caller
// can forget -- and because sqlc runs with emit_interface: false, dropping the
// predicate from a query breaks the build at every call site.
//
// New file queries belong in this section and MUST carry the predicate.
// ===========================================================================
func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, createFile,
		arg.Slug,
		arg.Name,
		arg.HtmlContent,
		arg.Kind,
		arg.IsPublic,
		arg.AccessCode,
		arg.UserID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
	)
	return i, err
}

const expireFile = `-- name: ExpireFile :exec
UPDATE files
SET is_public = 0, expires_at = NULL, max_views = NULL
WHERE slug = ? AND deleted_at IS NULL
`

func (q *Queries) ExpireFile(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, expireFile, slug)
	return err
}

const getFileBySlugAnyOwner = `-- name: GetFileBySlugAnyOwner :one

SELECT id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id FROM files
WHERE slug = ? AND deleted_at IS NULL
`

// ===========================================================================
// UNSCOPED -- the public render path (GET /res/{slug}) only.
//
// These serve anonymous visitors holding a share link, who have no user at
// all, so they cannot be owner-scoped without breaking every public link.
// NEVER call anything below this line from a handler behind requireAuth --
// that is exactly how the IDOR this section exists to prevent was introduced.
// See FilesHandler.Render.
// ===========================================================================
func (q *Queries) GetFileBySlugAnyOwner(ctx context.Context, slug string) (File, error) {
	row := q.db.QueryRowContext(ctx, getFileBySlugAnyOwner, slug)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
	)
	return i, err
}

const getUserFileBySlug = `-- name: GetUserFileBySlug :one
SELECT id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id FROM files
WHERE slug = ?1 AND user_id = ?2 AND deleted_at IS NULL
`

type GetUserFileBySlugParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) GetUserFileBySlug(ctx context.Context, arg GetUserFileBySlugParams) (File, error) {
	row := q.db.QueryRowContext(ctx, getUserFileBySlug, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
	)
	return i, err
}

const hardDeleteFile = `-- name: HardDeleteFile :execrows
DELETE FROM files
WHERE slug = ?1 AND user_id = ?2 AND deleted_at IS NOT NULL
`

type HardDeleteFileParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) HardDeleteFile(ctx context.Context, arg HardDeleteFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, hardDeleteFile, arg.Slug, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const incrementFileCodeSuccessCount = `-- name: IncrementFileCodeSuccessCount :exec
UPDATE files
SET code_success_count = code_success_count + 1
WHERE slug = ? AND deleted_at IS NULL
`

func (q *Queries) IncrementFileCodeSuccessCount(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, incrementFileCodeSuccessCount, slug)
	return err
}

const incrementFileFailureCount = `-- name: IncrementFileFailureCount :exec
UPDATE files
SET failure_count = failure_count + 1
WHERE slug = ? AND deleted_at IS NULL
`

func (q *Queries) IncrementFileFailureCount(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, incrementFileFailureCount, slug)
	return err
}

const incrementFileSuccessCount = `-- name: IncrementFileSuccessCount :exec
UPDATE files
SET success_count = success_count + 1
WHERE slug = ? AND deleted_at IS NULL
`

func (q *Queries) IncrementFileSuccessCount(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, incrementFileSuccessCount, slug)
	return err
}

const incrementFileViewCount = `-- name: IncrementFileViewCount :exec
UPDATE files
SET view_count = view_count + 1
WHERE slug = ? AND deleted_at IS NULL
`

func (q *Queries) IncrementFileViewCount(ctx context.Context, slug string) error {
	_, err := q.db.ExecContext(ctx, incrementFileViewCount, slug)
	return err
}

const listUserDeletedFiles = `-- name: ListUserDeletedFiles :many
SELECT id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id FROM files
WHERE deleted_at IS NOT NULL AND user_id = ?1
ORDER BY deleted_at DESC
`

func (q *Queries) ListUserDeletedFiles(ctx context.Context, userID int64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listUserDeletedFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.HtmlContent,
			&i.IsPublic,
			&i.AccessCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SuccessCount,
			&i.FailureCount,
			&i.Tags,
			&i.ExpiresAt,
			&i.MaxViews,
			&i.ViewCount,
			&i.Kind,
			&i.CodeSuccessCount,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserFiles = `-- name: ListUserFiles :many
SELECT id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id FROM files
WHERE deleted_at IS NULL AND user_id = ?1
ORDER BY created_at DESC
`

func (q *Queries) ListUserFiles(ctx context.Context, userID int64) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, listUserFiles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.HtmlContent,
			&i.IsPublic,
			&i.AccessCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SuccessCount,
			&i.FailureCount,
			&i.Tags,
			&i.ExpiresAt,
			&i.MaxViews,
			&i.ViewCount,
			&i.Kind,
			&i.CodeSuccessCount,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshFileAccessCode = `-- name: RefreshFileAccessCode :one
UPDATE files
SET access_code = ?1, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?2 AND user_id = ?3 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id
`

type RefreshFileAccessCodeParams struct {
	AccessCode string `json:"access_code"`
	Slug       string `json:"slug"`
	UserID     int64  `json:"user_id"`
}

func (q *Queries) RefreshFileAccessCode(ctx context.Context, arg RefreshFileAccessCodeParams) (File, error) {
	row := q.db.QueryRowContext(ctx, refreshFileAccessCode, arg.AccessCode, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
	)
	return i, err
}

const renameFile = `-- name: RenameFile :one
UPDATE files
SET name = ?1, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?2 AND user_id = ?3 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id
`

type RenameFileParams struct {
	Name   string `json:"name"`
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) RenameFile(ctx context.Context, arg RenameFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, renameFile, arg.Name, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
	)
	return i, err
}

const restoreFile = `-- name: RestoreFile :one
UPDATE files
SET deleted_at = NULL, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?1 AND user_id = ?2 AND deleted_at IS NOT NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id
`

type RestoreFileParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) RestoreFile(ctx context.Context, arg RestoreFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, restoreFile, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
	)
	return i, err
}

const searchUserFilesByName = `-- name: SearchUserFilesByName :many

SELECT id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id FROM files
WHERE deleted_at IS NULL AND user_id = ?1
  AND instr(lower(name), lower(?2)) > 0
ORDER BY created_at DESC
`

type SearchUserFilesByNameParams struct {
	UserID    int64  `json:"user_id"`
	NameQuery string `json:"name_query"`
}

// Plain substring search via instr() rather than LIKE: no wildcard/escape
// handling needed, and lower() gives the same ASCII-only case-insensitivity
// LIKE would.
func (q *Queries) SearchUserFilesByName(ctx context.Context, arg SearchUserFilesByNameParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, searchUserFilesByName, arg.UserID, arg.NameQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.HtmlContent,
			&i.IsPublic,
			&i.AccessCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SuccessCount,
			&i.FailureCount,
			&i.Tags,
			&i.ExpiresAt,
			&i.MaxViews,
			&i.ViewCount,
			&i.Kind,
			&i.CodeSuccessCount,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchUserFilesWithContent = `-- name: SearchUserFilesWithContent :many
SELECT id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id FROM files
WHERE deleted_at IS NULL AND user_id = ?1
  AND (instr(lower(name), lower(?2)) > 0
    OR instr(lower(html_content), lower(?3)) > 0)
ORDER BY created_at DESC
`

type SearchUserFilesWithContentParams struct {
	UserID       int64  `json:"user_id"`
	NameQuery    string `json:"name_query"`
	ContentQuery string `json:"content_query"`
}

func (q *Queries) SearchUserFilesWithContent(ctx context.Context, arg SearchUserFilesWithContentParams) ([]File, error) {
	rows, err := q.db.QueryContext(ctx, searchUserFilesWithContent, arg.UserID, arg.NameQuery, arg.ContentQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []File
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.HtmlContent,
			&i.IsPublic,
			&i.AccessCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.SuccessCount,
			&i.FailureCount,
			&i.Tags,
			&i.ExpiresAt,
			&i.MaxViews,
			&i.ViewCount,
			&i.Kind,
			&i.CodeSuccessCount,
			&i.UserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setFileExpiry = `-- name: SetFileExpiry :one
UPDATE files
SET is_public = 1,
    expires_at = ?1,
    max_views = ?2,
    view_count = 0,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = ?3 AND user_id = ?4 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id
`

type SetFileExpiryParams struct {
	ExpiresAt sql.NullTime  `json:"expires_at"`
	MaxViews  sql.NullInt64 `json:"max_views"`
	Slug      string        `json:"slug"`
	UserID    int64         `json:"user_id"`
}

func (q *Queries) SetFileExpiry(ctx context.Context, arg SetFileExpiryParams) (File, error) {
	row := q.db.QueryRowContext(ctx, setFileExpiry,
		arg.ExpiresAt,
		arg.MaxViews,
		arg.Slug,
		arg.UserID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
	)
	return i, err
}

const setFileTags = `-- name: SetFileTags :one
UPDATE files
SET tags = ?1, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?2 AND user_id = ?3 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id
`

type SetFileTagsParams struct {
	Tags   string `json:"tags"`
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

func (q *Queries) SetFileTags(ctx context.Context, arg SetFileTagsParams) (File, error) {
	row := q.db.QueryRowContext(ctx, setFileTags, arg.Tags, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
	)
	return i, err
}

const setFileVisibility = `-- name: SetFileVisibility :one
UPDATE files
SET is_public = ?1, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?2 AND user_id = ?3 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id
`

type SetFileVisibilityParams struct {
	IsPublic bool   `json:"is_public"`
	Slug     string `json:"slug"`
	UserID   int64  `json:"user_id"`
}

func (q *Queries) SetFileVisibility(ctx context.Context, arg SetFileVisibilityParams) (File, error) {
	row := q.db.QueryRowContext(ctx, setFileVisibility, arg.IsPublic, arg.Slug, arg.UserID)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
	)
	return i, err
}

const softDeleteFile = `-- name: SoftDeleteFile :execrows
UPDATE files
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE slug = ?1 AND user_id = ?2 AND deleted_at IS NULL
`

type SoftDeleteFileParams struct {
	Slug   string `json:"slug"`
	UserID int64  `json:"user_id"`
}

// :execrows rather than :exec so the handler can tell "soft-deleted it" from
// "matched nothing" and 404 instead of reporting a success-shaped no-op.
func (q *Queries) SoftDeleteFile(ctx context.Context, arg SoftDeleteFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, softDeleteFile, arg.Slug, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateFile = `-- name: UpdateFile :one
UPDATE files
SET name = ?1,
    slug = ?2,
    html_content = ?3,
    access_code = ?4,
    updated_at = CURRENT_TIMESTAMP
WHERE slug = ?5 AND user_id = ?6 AND deleted_at IS NULL
RETURNING id, slug, name, html_content, is_public, access_code, created_at, updated_at, deleted_at, success_count, failure_count, tags, expires_at, max_views, view_count, kind, code_success_count, user_id
`

type UpdateFileParams struct {
	Name        string `json:"name"`
	NewSlug     string `json:"new_slug"`
	HtmlContent string `json:"html_content"`
	AccessCode  string `json:"access_code"`
	Slug        string `json:"slug"`
	UserID      int64  `json:"user_id"`
}

// The SET slug and the WHERE slug are different values; naming both explicitly
// keeps them from being mixed up (and avoids sqlc's generated `Slug_2` field).
func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) (File, error) {
	row := q.db.QueryRowContext(ctx, updateFile,
		arg.Name,
		arg.NewSlug,
		arg.HtmlContent,
		arg.AccessCode,
		arg.Slug,
		arg.UserID,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.HtmlContent,
		&i.IsPublic,
		&i.AccessCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.SuccessCount,
		&i.FailureCount,
		&i.Tags,
		&i.ExpiresAt,
		&i.MaxViews,
		&i.ViewCount,
		&i.Kind,
		&i.CodeSuccessCount,
		&i.UserID,
	)
	return i, err
}
