// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Config struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type File struct {
	ID               int64         `json:"id"`
	Slug             string        `json:"slug"`
	Name             string        `json:"name"`
	HtmlContent      string        `json:"html_content"`
	IsPublic         bool          `json:"is_public"`
	AccessCode       string        `json:"access_code"`
	CreatedAt        time.Time     `json:"created_at"`
	UpdatedAt        time.Time     `json:"updated_at"`
	DeletedAt        sql.NullTime  `json:"deleted_at"`
	SuccessCount     int64         `json:"success_count"`
	FailureCount     int64         `json:"failure_count"`
	Tags             string        `json:"tags"`
	ExpiresAt        sql.NullTime  `json:"expires_at"`
	MaxViews         sql.NullInt64 `json:"max_views"`
	ViewCount        int64         `json:"view_count"`
	Kind             string        `json:"kind"`
	CodeSuccessCount int64         `json:"code_success_count"`
	UserID           int64         `json:"user_id"`
}

type Session struct {
	Token     string    `json:"token"`
	CreatedAt time.Time `json:"created_at"`
	ExpiresAt time.Time `json:"expires_at"`
	UserID    int64     `json:"user_id"`
}

type User struct {
	ID           int64          `json:"id"`
	Username     string         `json:"username"`
	Nickname     string         `json:"nickname"`
	PasswordHash string         `json:"password_hash"`
	ApiKey       sql.NullString `json:"api_key"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
