// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlcgen

import (
	"context"
	"time"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at)
VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string    `json:"token"`
	UserID    int64     `json:"user_id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE unixepoch(expires_at) IS NULL OR unixepoch(expires_at) <= unixepoch('now')
`

// The IS NULL arm sweeps rows whose expires_at unixepoch() cannot parse:
// GetValidSession already treats them as expired, and without this they would
// never be collected.
func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const deleteUserSessions = `-- name: DeleteUserSessions :exec
DELETE FROM sessions
WHERE user_id = ?
`

// Every session of one user, for the privileged actions that must end a
// suspended or password-reset account's access right now rather than whenever
// its cookies happen to expire.
func (q *Queries) DeleteUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.ExecContext(ctx, deleteUserSessions, userID)
	return err
}

const getValidSession = `-- name: GetValidSession :one
SELECT token, created_at, expires_at, user_id FROM sessions
WHERE token = ? AND unixepoch(expires_at) > unixepoch('now')
`

// Expiry is compared through unixepoch() rather than as text: this column holds
// an ISO-8601 UTC string written by the driver, CURRENT_TIMESTAMP produces a
// bare 'YYYY-MM-DD HH:MM:SS', and a plain '>' between the two would be a
// lexicographic comparison of two different shapes. unixepoch() reduces both to
// an instant. A value it cannot parse yields NULL, so such a row is never valid
// -- the fail-closed direction.
func (q *Queries) GetValidSession(ctx context.Context, token string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getValidSession, token)
	var i Session
	err := row.Scan(
		&i.Token,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UserID,
	)
	return i, err
}
